### ISSUE TITLE
[Bug] [Guilds] Two bugs found after minor testing. Latest version. GUI and /n color.

### ISSUE THREAD

**Issue by Wextra** [Senre-MC/senre-mc.github.io#3]
![image](https://user-images.githubusercontent.com/35235942/131699058-bdb31de0-8af3-4a62-a1be-f43177f3539a.png)

This is what one sees when executing /g map gui. The console log presents the following information:

[guibuglogs.txt](https://github.com/Senre-MC/senre-mc.github.io/files/7092405/guibuglogs.txt)

--------

/n color still does not work. Only presents player with the Command Not Recognized prompt.

--------

**Comment by Senre-MC** [comment]
/g map gui has been added to the issues, formatted accordingly.

> /n color still does not work. Only presents player with the Command Not Recognized prompt.
Be more specific. I need to know how it doesn't work

**Comment by Senre-MC** [comment]
The /n color glitch has been added into code with the details provided in DM's
