### ISSUE TITLE
/s claim does not work

### ISSUE THREAD

**Issue by Wextra** [Senre-MC/senre-mc.github.io#5]
When executing /s claim on wilderness, player gets message "You cannot integrate this claim".

When executing /s claim on empty nation lands, player gets message "Your claims overlap with another".

**Comment by Senre-MC** [comment]
For the former, that's intentional. I'm not able to consider this even an evil data to reword what went wrong, or to avoid decieving players, that is literally how it works.

But the latter is quite important, I'll need to find out where it's gone wrong. I've written that down.
